"""Boss Wind (Sky Owl) SFX - synthesised (Tools/sfx/synth.py + synth_owl.py) so each sound matches its move (D-111)."""
from sfxtypes import S, Synth

ENTRIES = {
    "sfx.bossowl.volley_windup": S("Boss", [Synth("wing_flaps", seed=1, dur=0.8, beats=2)], vol=0.7, cooldown=0.2, desc="Wings draw back before the feather volley"),
    "sfx.bossowl.volley_fling": S("Boss", [Synth("feather_volley", seed=1, dur=0.9), Synth("feather_volley", seed=2, dur=0.85)],
                                  vol=0.9, jitter=0.03, cooldown=0.2, desc="Wings fling out a fan of feathers"),
    "sfx.bossowl.feather_hit": S("Boss", [Synth("feather", seed=5, dur=0.4), Synth("feather", seed=6, dur=0.35)],
                                 vol=0.6, jitter=0.05, cooldown=0.05, voices=3, desc="A feather hits the player"),
    "sfx.bossowl.takeoff": S("Boss", [Synth("wing_flaps", seed=3, dur=1.1, beats=4)], vol=0.85, cooldown=0.3, desc="Owl beats its wings and rises out of sight"),
    "sfx.bossowl.dive_warning": S("Boss", [Synth("wind_dive", seed=1, dur=1.4)], vol=0.7, cooldown=0.4, desc="A shadow grows: the owl is coming down"),
    "sfx.bossowl.dive_hit": S("Boss", [Synth("wind_shockwave", seed=2, dur=1.3)], vol=1.0, cooldown=0.3, desc="Owl slams down on the target"),
    "sfx.bossowl.cyclone_cast": S("Boss", [Synth("wing_flaps", seed=7, dur=1.0, beats=5)], vol=0.8, cooldown=0.3, desc="Rapid wing beats stir up cyclones"),
    "sfx.bossowl.cyclone_loop": S("Boss", [Synth("cyclone_spin", seed=1, dur=2.4, xfade=0.5)], vol=0.5, loop=True, desc="A cyclone wanders the platform"),
    "sfx.bossowl.cyclone_hit": S("Boss", [Synth("wind_catch", seed=3, dur=0.5)], vol=0.8, cooldown=0.2, desc="Cyclone throws the player"),
    "sfx.bossowl.wall_warning": S("Boss", [Synth("wind_charge", seed=4, dur=1.5)], vol=0.7, cooldown=0.4, desc="Owl banks and the gale gathers"),
    "sfx.bossowl.wall_rush": S("Boss", [Synth("gale_wall", seed=1, dur=1.8)], vol=0.85, cooldown=0.4, desc="The wall of wind sweeps across the platform"),
    "sfx.bossowl.wall_hit": S("Boss", [Synth("wind_slam", seed=3, dur=0.6)], vol=0.9, cooldown=0.3, desc="Wall hits the player"),
    "sfx.bossowl.slash_windup": S("Boss", [Synth("wing_flaps", seed=9, dur=0.9, beats=2)], vol=0.65, cooldown=0.2, desc="Wings lift before the blades"),
    "sfx.bossowl.blade_cut": S("Boss", [Synth("blade_cut", seed=1, dur=0.6), Synth("blade_cut", seed=2, dur=0.55), Synth("blade_cut", seed=3, dur=0.65)],
                               vol=0.85, jitter=0.04, cooldown=0.1, voices=3, desc="Crescent blades fly out"),
    "sfx.bossowl.blade_hit": S("Boss", [Synth("wind_catch", seed=8, dur=0.4)], vol=0.8, cooldown=0.1, desc="A blade cuts the player"),
    "sfx.bossowl.storm_charge": S("Boss", [Synth("storm_charge", seed=1, dur=2.4)], vol=0.85, cooldown=0.5, desc="Owl circles overhead as the storm builds"),
    "sfx.bossowl.floor_warn": S("Boss", [Synth("floor_warn", seed=1, dur=0.9)], vol=0.5, cooldown=0.4, desc="A section of floor starts to flicker"),
    "sfx.bossowl.floor_break": S("Boss", [Synth("floor_break", seed=1, dur=1.0), Synth("floor_break", seed=2, dur=1.1)],
                                 vol=0.95, jitter=0.03, cooldown=0.3, desc="A floor section breaks away"),
    "sfx.bossowl.storm_end": S("Boss", [Synth("wind_land", seed=2, dur=0.7)], vol=0.8, cooldown=0.4, desc="The storm dies and the owl drops, spent"),
    "sfx.bossowl.awaken": S("Boss", [Synth("owl_hoot", seed=1, dur=1.2), Synth("owl_screech", seed=1, dur=1.5)], vol=1.0, desc="Owl awakens"),
    "sfx.bossowl.phase_roar": S("Boss", [Synth("owl_screech", seed=2, dur=1.6), Synth("owl_screech", seed=3, dur=1.5)], vol=1.0, desc="Phase change screech"),
    "sfx.bossowl.hit": S("Boss", [Synth("owl_hurt", seed=1, dur=0.4), Synth("owl_hurt", seed=2, dur=0.38), Synth("owl_hurt", seed=3, dur=0.42)],
                         vol=0.65, jitter=0.05, cooldown=0.06, voices=3, desc="Owl takes damage"),
    "sfx.bossowl.recovery": S("Boss", [Synth("wind_land", seed=5, dur=0.9)], vol=0.7, desc="Owl lands, winded"),
    "sfx.bossowl.death": S("Boss", [Synth("owl_death", seed=1, dur=2.4)], vol=1.0, desc="Owl falls"),
}
