"""Generates Assets/Scripts/Audio/SfxIds.cs (string constants) from Assets/Editor/Sfx/sfx_catalog.json."""
import json, os, re
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
cat = json.load(open(os.path.join(ROOT, "Assets/Editor/Sfx/sfx_catalog.json"), encoding="utf-8"))["entries"]
ids = sorted({e["id"] for e in cat} | {"sfx.ui.hover", "sfx.ui.click_primary", "sfx.ui.click_secondary", "sfx.ui.toggle",
                                      "sfx.ui.error", "sfx.ui.popup_open", "sfx.ui.popup_close"})
def name(i):
    return "".join(p.capitalize() if not p.isdigit() else p for p in re.split(r"[._]", i[4:]))
out = ["// <auto-generated> by Tools/sfx/gen_ids.py - do not edit; re-run after changing the catalogs.", "",
       "/// <summary>Every SFX id of the game (SoundFXLibrary group names).</summary>", "public static class SfxIds", "{"]
seen = set()
for i in ids:
    n = name(i)
    assert n not in seen, n
    seen.add(n)
    out.append(f'    public const string {n} = "{i}";')
out.append("}")
open(os.path.join(ROOT, "Assets/Scripts/Audio/SfxIds.cs"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print(len(ids), "ids")
